"""
SkillBridge AI Engine & Career Coach
Powered by Google Gemini Studio (gemini-flash-latest)
Grounded on:
- Analytics Jobs.csv (15,841 job postings)
- DataScience Jobs.csv (1,602 company salary benchmarks)
- JDS Skill Traits.xlsx (139 junior candidate assessments & salary hike predictors)
- SDS Personality Traits.xlsx (161 senior candidate evaluations)
- engineering_jobs.csv (623 LinkedIn postings with direct application links)
"""

import os
import sys
import json
import argparse
from http.server import HTTPServer, BaseHTTPRequestHandler
import urllib.parse
import urllib.request

# Ensure UTF-8 output on Windows terminal
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

GEMINI_API_KEY = os.environ.get(
    "GEMINI_API_KEY",
    "AQ.Ab8RN6JZc93LWZu3FY1iIhRnPfCqrM0MYvUhx56c4syj452b0w"
)
os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY
GEMINI_MODEL = "gemini-flash-latest"

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Robust path resolution for model file
model_candidates = [
    os.path.join(BASE_DIR, "gemini_trained_model.json"),
    os.path.join(BASE_DIR, "skillbridge", "gemini_trained_model.json"),
    os.path.join(BASE_DIR, "..", "gemini_trained_model.json")
]
MODEL_FILE = next((p for p in model_candidates if os.path.exists(p)), model_candidates[0])

# Robust path resolution for jobs dataset
jobs_candidates = [
    os.path.join(BASE_DIR, "frontend", "src", "lib", "datasetJobs.json"),
    os.path.join(BASE_DIR, "skillbridge", "frontend", "src", "lib", "datasetJobs.json"),
    os.path.join(BASE_DIR, "api", "datasetJobs.json"),
    os.path.join(BASE_DIR, "..", "skillbridge", "frontend", "src", "lib", "datasetJobs.json")
]
jobs_json_path = next((p for p in jobs_candidates if os.path.exists(p)), jobs_candidates[0])

# ─── 1. Load Trained Knowledge Model ───────────────────────────────────────────
print(f"Loading SkillBridge trained model from {MODEL_FILE}...")
trained_model = {}
if os.path.exists(MODEL_FILE):
    try:
        with open(MODEL_FILE, "r", encoding="utf-8") as f:
            trained_model = json.load(f)
        print("Trained Gemini model successfully loaded into memory!")
    except Exception as e:
        print(f"Warning: Failed to load trained model file: {e}")
else:
    print(f"Warning: {MODEL_FILE} not found. Running with baseline heuristics.")

# Load real jobs dataset
dataset_jobs = []
if os.path.exists(jobs_json_path):
    try:
        with open(jobs_json_path, "r", encoding="utf-8") as f:
            dataset_jobs = json.load(f)
        print(f"Loaded {len(dataset_jobs)} real tech job postings from {jobs_json_path}.")
    except Exception as e:
        print(f"Warning: Failed to load dataset jobs JSON: {e}")

# ─── 2. Google Gemini Studio Client ───────────────────────────────────────────
def call_gemini(prompt: str, system_instruction: str = "") -> str:
    """Invokes Google Gemini Studio API (gemini-flash-latest)."""
    # 1. Primary: Direct high-speed REST endpoint
    try:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={GEMINI_API_KEY}"
        payload = {
            "contents": [{"role": "user", "parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.4, "maxOutputTokens": 1200}
        }
        if system_instruction:
            payload["systemInstruction"] = {"parts": [{"text": system_instruction}]}
        
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"}
        )
        with urllib.request.urlopen(req, timeout=25) as res:
            res_data = json.loads(res.read().decode("utf-8"))
            return res_data["candidates"][0]["content"]["parts"][0]["text"]
    except Exception as rest_err:
        pass

    # 2. Fallback: Google GenAI Python SDK
    try:
        from google import genai
        client = genai.Client(api_key=GEMINI_API_KEY)
        full_prompt = prompt
        if system_instruction:
            full_prompt = f"System Instruction:\n{system_instruction}\n\nUser Prompt:\n{prompt}"
            
        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=full_prompt
        )
        if response and response.text:
            return response.text
    except Exception as sdk_err:
        return f"Error connecting to Gemini Studio: {sdk_err}"
            
    return "No response generated by Gemini."

# ─── 3. Domain Logic & Recommendation Systems ──────────────────────────────────
COURSE_CATALOG = {
    "Python": {"title": "CS50P: Introduction to Programming with Python", "platform": "Harvard / edX", "url": "https://cs50.harvard.edu/python/", "duration": "6 Weeks"},
    "SQL": {"title": "Interactive SQL Masterclass & Mode Bootcamp", "platform": "SQLBolt & Mode", "url": "https://sqlbolt.com/", "duration": "2 Weeks"},
    "Machine Learning": {"title": "Machine Learning Specialization", "platform": "DeepLearning.AI / Andrew Ng", "url": "https://www.coursera.org/specializations/machine-learning-introduction", "duration": "8 Weeks"},
    "Deep Learning": {"title": "Practical Deep Learning for Coders", "platform": "fast.ai", "url": "https://course.fast.ai/", "duration": "7 Weeks"},
    "PyTorch": {"title": "Deep Learning with PyTorch: A 60 Minute Blitz", "platform": "pytorch.org", "url": "https://pytorch.org/tutorials/", "duration": "3 Weeks"},
    "Docker": {"title": "Containerization & Microservices Fundamentals", "platform": "Docker Docs", "url": "https://docs.docker.com/get-started/", "duration": "2 Weeks"},
    "Kubernetes": {"title": "Kubernetes Interactive Tutorials & Labs", "platform": "kubernetes.io", "url": "https://kubernetes.io/docs/tutorials/", "duration": "4 Weeks"},
    "AWS": {"title": "AWS Cloud Practitioner Essentials", "platform": "AWS Skill Builder", "url": "https://explore.skillbuilder.aws/", "duration": "3 Weeks"},
    "Data Structures": {"title": "NeetCode 150 Coding Interview Roadmap", "platform": "NeetCode.io", "url": "https://neetcode.io/roadmap", "duration": "8 Weeks"},
    "MLOps": {"title": "Production Machine Learning & MLOps", "platform": "Made With ML", "url": "https://madewithml.com/", "duration": "5 Weeks"},
    "FastAPI": {"title": "High Performance Async Microservices in Python", "platform": "fastapi.tiangolo.com", "url": "https://fastapi.tiangolo.com/", "duration": "2 Weeks"},
}

def recommend_jobs(user_skills: list, city: str = "", max_years: int = None, limit: int = 5):
    """Recommends matching tech postings from the real LinkedIn dataset."""
    u_skills_set = set(s.strip().lower() for s in user_skills if s)
    matches = []
    
    for job in dataset_jobs:
        j_skills = [s.strip().lower() for s in job.get("skills", [])]
        hits = [s for s in j_skills if s in u_skills_set]
        miss = [s for s in j_skills if s not in u_skills_set]
        
        pct = round((len(hits) / len(j_skills) * 100)) if j_skills else 0
        
        if city and city.lower() not in job.get("location", "").lower():
            continue
            
        if max_years is not None:
            min_y = job.get("min_years", 0)
            if min_y > max_years:
                continue
                
        matches.append({
            "title": job.get("title"),
            "company": job.get("company"),
            "location": job.get("location"),
            "match_percent": pct,
            "you_have": [s.title() for s in hits],
            "you_miss": [s.title() for s in miss],
            "apply_link": job.get("apply_link", "https://linkedin.com"),
            "skills": job.get("skills", [])
        })
        
    matches.sort(key=lambda x: x["match_percent"], reverse=True)
    return matches[:limit]

def analyze_skill_gap(target_role: str, user_skills: list):
    """Evaluates candidate against role competencies and returns prioritized gaps."""
    role_key = target_role.lower().replace(" ", "-")
    comp_map = trained_model.get("synthesis", {}).get("role_competencies", {})
    
    matched_role = None
    for k, v in comp_map.items():
        if k in role_key or role_key in k:
            matched_role = v
            break
            
    if not matched_role:
        core_skills = ["Python", "SQL", "Machine Learning", "Docker", "PyTorch", "MLOps"]
        salary_range = "14-35 LPA"
    else:
        core_skills = matched_role.get("core_skills", [])
        salary_range = matched_role.get("salary_range", "12-30 LPA")
        
    user_skills_lower = [s.strip().lower() for s in user_skills]
    have = [s for s in core_skills if s.lower() in user_skills_lower]
    missing = [s for s in core_skills if s.lower() not in user_skills_lower]
    readiness = round((len(have) / len(core_skills)) * 100) if core_skills else 0
    
    courses = [COURSE_CATALOG.get(m, {"title": f"{m} Masterclass", "platform": "Official Docs", "url": "https://google.com"}) for m in missing]
    
    return {
        "target_role": target_role,
        "readiness_percent": readiness,
        "salary_range_lpa": salary_range,
        "skills_possessed": have,
        "priority_gaps": missing,
        "recommended_courses": courses
    }

def recommend_courses(skills_list: list):
    """Returns curated free courses for the provided skills."""
    recs = []
    for s in skills_list:
        c = COURSE_CATALOG.get(s.strip().title())
        if c:
            recs.append({"skill": s, **c})
        else:
            recs.append({
                "skill": s,
                "title": f"Interactive {s} Practice Sandbox",
                "platform": "SkillBridge Code Lab",
                "url": "https://github.com",
                "duration": "2 Weeks"
            })
    return recs

def chat_career_coach(message: str, context: dict = None) -> str:
    """Conversational Career Coach powered by Google Gemini Studio."""
    context = context or {}
    user_skills = context.get("skills", ["Python", "SQL"])
    target_role = context.get("target_role", "Machine Learning Engineer")
    city = context.get("city", "Bengaluru")
    
    grounding = trained_model.get("synthesis", {}).get("system_prompt_grounding", 
        "You are the Chief AI Career Coach at SkillBridge India, trained on 18,000+ job postings."
    )
    
    # Ground prompt with dataset tools
    jobs = recommend_jobs(user_skills, city=city, limit=3)
    gap = analyze_skill_gap(target_role, user_skills)
    
    prompt = f"""Candidate Question: "{message}"
Candidate Profile:
- Skills: {', '.join(user_skills)}
- Target Role: {target_role}
- City: {city}
- Readiness Score: {gap['readiness_percent']}%
- Empirical Salary Band: {gap['salary_range_lpa']}
- Top Gaps: {', '.join(gap['priority_gaps'])}

Top Matching Real LinkedIn Jobs:
{json.dumps(jobs, indent=2)}

Provide a sharp, encouraging, and prescriptive advisory response formatted with GitHub markdown."""
    
    return call_gemini(prompt, system_instruction=grounding)

# ─── 4. Standalone HTTP Server for Local Web Integration ───────────────────────
class SkillBridgeHandler(BaseHTTPRequestHandler):
    def _send_json(self, status: int, data: dict):
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
        self.wfile.write(json.dumps(data).encode("utf-8"))

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_POST(self):
        content_length = int(self.headers.get("Content-Length", 0))
        post_data = self.rfile.read(content_length)
        body = json.loads(post_data.decode("utf-8")) if post_data else {}
        
        path = self.path.split("?")[0]
        
        if path == "/api/ai" or path == "/api/chat":
            msg = body.get("message", "")
            ctx = body.get("context", {})
            reply = chat_career_coach(msg, ctx)
            return self._send_json(200, {"reply": reply, "source": "gemini-flash-latest"})
            
        elif path == "/api/recommend/jobs":
            skills = body.get("skills", [])
            city = body.get("city", "")
            results = recommend_jobs(skills, city=city, limit=body.get("limit", 10))
            return self._send_json(200, {"jobs": results, "count": len(results)})
            
        elif path == "/api/analyze/gap":
            role = body.get("target_role", "Machine Learning Engineer")
            skills = body.get("skills", [])
            gap = analyze_skill_gap(role, skills)
            return self._send_json(200, gap)
            
        elif path == "/api/recommend/courses":
            skills = body.get("skills", [])
            courses = recommend_courses(skills)
            return self._send_json(200, {"courses": courses})
            
        self._send_json(404, {"error": "Not Found"})

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        params = urllib.parse.parse_qs(parsed.query)
        
        if parsed.path == "/api/health":
            return self._send_json(200, {
                "status": "online",
                "model": "gemini-flash-latest",
                "datasets_loaded": True,
                "jobs_count": len(dataset_jobs)
            })
            
        elif parsed.path == "/api/insights":
            role = params.get("role", ["Data Scientist"])[0]
            role_benchmarks = trained_model.get("ds_stats", {}).get("role_benchmarks", {})
            return self._send_json(200, {
                "benchmarks": role_benchmarks,
                "total_jobs": len(dataset_jobs)
            })
            
        self._send_json(404, {"error": "Not Found"})

def run_server(port: int = 5050):
    server = HTTPServer(("0.0.0.0", port), SkillBridgeHandler)
    print(f"🚀 SkillBridge Gemini Python Server listening on http://localhost:{port}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down server.")
        server.server_close()

# ─── 5. CLI & Test Mode ────────────────────────────────────────────────────────
def run_cli():
    print("=" * 65)
    print("🤖 SkillBridge AI Career Coach (Python + Google Gemini Studio)")
    print("   Calibrated on 18,000+ Indian job postings & candidate traits")
    print("=" * 65)
    print("Type your question, or commands:")
    print("  'jobs <skill1, skill2>'  -> Recommend matching LinkedIn jobs")
    print("  'gap <role>'             -> Analyze skill gap & salary forecast")
    print("  'courses <skill1, skill2>'-> Recommend verified free courses")
    print("  'exit'                   -> Quit")
    print("-" * 65)
    
    while True:
        try:
            line = input("\n👤 You: ").strip()
            if not line:
                continue
            if line.lower() in ["exit", "quit", "q"]:
                break
                
            if line.lower().startswith("jobs "):
                skills_str = line[5:].strip()
                skills = [s.strip() for s in skills_str.split(",") if s.strip()]
                recs = recommend_jobs(skills, limit=5)
                print(f"\n💼 Found {len(recs)} Top Matching Jobs:")
                for i, r in enumerate(recs, 1):
                    print(f"  {i}. {r['title']} @ {r['company']} ({r['location']}) - {r['match_percent']}% Match")
                    print(f"     Skills: {', '.join(r['skills'][:6])}")
                    print(f"     Apply: {r['apply_link']}")
            elif line.lower().startswith("gap "):
                role = line[4:].strip()
                skills = ["Python", "SQL"]
                gap = analyze_skill_gap(role, skills)
                print(f"\n🎯 Skill Gap Analysis for {gap['target_role']}:")
                print(f"  • Readiness: {gap['readiness_percent']}%")
                print(f"  • Expected Salary: {gap['salary_range_lpa']}")
                print(f"  • Priority Gaps: {', '.join(gap['priority_gaps'])}")
                print(f"  • Recommended Courses:")
                for c in gap['recommended_courses']:
                    print(f"    - {c['title']} ({c.get('platform', 'Web')}) -> {c.get('url', '#')}")
            else:
                print("Thinking with Gemini Studio...")
                reply = chat_career_coach(line, {"skills": ["Python", "SQL", "Docker"], "city": "Bengaluru"})
                print(f"\n🤖 Coach Gemini:\n{reply}")
        except (KeyboardInterrupt, EOFError):
            break

def run_tests():
    print("\n--- Running Automated Verification Tests ---")
    
    # 1. Test Job Recommendation
    print("1. Testing Job Recommendation System...")
    jobs = recommend_jobs(["Python", "Machine Learning", "PyTorch"], limit=3)
    assert len(jobs) > 0, "Job recommendation should return jobs"
    print(f"   Success! Top job: {jobs[0]['title']} @ {jobs[0]['company']} (Match: {jobs[0]['match_percent']}%)")
    
    # 2. Test Skill Gap Analysis
    print("2. Testing Skill Gap Analysis...")
    gap = analyze_skill_gap("Machine Learning Engineer", ["Python", "SQL"])
    assert "salary_range_lpa" in gap, "Gap analysis must contain salary range"
    print(f"   Success! Readiness: {gap['readiness_percent']}%, Gaps: {gap['priority_gaps']}")
    
    # 3. Test Course Recommendation
    print("3. Testing Course Recommendation...")
    courses = recommend_courses(["Docker", "PyTorch"])
    assert len(courses) == 2, "Should return 2 courses"
    print(f"   Success! Courses returned: {[c['title'] for c in courses]}")
    
    # 4. Test Live Gemini Chat
    print("4. Testing Live Gemini Studio Career Coach API...")
    query = "Suggest the fastest path to 25 LPA as an ML Engineer in Bengaluru."
    response = chat_career_coach(query, {"skills": ["Python", "SQL"], "target_role": "Machine Learning Engineer"})
    assert len(response) > 50, "Gemini should return a detailed response"
    print(f"   Success! Gemini generated {len(response)} chars response.")
    print("\nPreview of Gemini response:")
    print(response[:300] + "...\n")
    print("ALL TESTS PASSED WITH 100% SUCCESS!")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SkillBridge Gemini AI Engine")
    parser.add_argument("--serve", action="store_true", help="Run local HTTP microservice")
    parser.add_argument("--port", type=int, default=5050, help="Port for HTTP microservice (default: 5050)")
    parser.add_argument("--test", action="store_true", help="Run automated verification tests")
    
    args = parser.parse_args()
    
    if args.test:
        run_tests()
    elif args.serve:
        run_server(args.port)
    else:
        run_cli()